name = "jsonrpc"
version = "1.0.0"

description = "Encoders and decoders for JSON-RPC 2.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ryanmiville", repo = "jsonrpc" }
links = [{ title = "JSON-RPC", href = "https://www.jsonrpc.org/" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.6 and < 2.0.0"
